FROM node:20-alpine

# 安装 pnpm
RUN npm install -g pnpm

WORKDIR /app

# 复制运行应用所需的文件。
# 这些文件应由 CI/CD 流程中的上一个构建步骤提供。
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY next.config.ts ./
COPY .next ./.next
COPY public ./public

# 只安装生产依赖。
# 使用 pnpm 以获得更快、更可靠的安装。
RUN pnpm install --prod --frozen-lockfile

# 设置生产环境变量
ENV NODE_ENV production

# 暴露应用运行的端口
EXPOSE 3000

# 启动应用的命令
CMD ["pnpm", "start"] 