FROM node:20-alpine

WORKDIR /app

# 复制运行应用所需的文件。
# 这些文件应由 CI/CD 流程中的上一个构建步骤提供。
COPY package.json ./
COPY package-lock.json ./
COPY next.config.ts ./
COPY .next ./.next
COPY public ./public

# 只安装生产依赖。
# 使用 npm ci 以获得更快、更可靠的安装。
RUN npm ci --only=production

# 设置生产环境变量
ENV NODE_ENV production

# 暴露应用运行的端口
EXPOSE 3000

# 启动应用的命令
CMD ["npm", "start"] 