name: Deploy Client

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'ENDSSH'
            cd /root/splendor-client
            
            # 保存日志并拉取代码
            mkdir -p logs
            docker-compose logs > logs/backup-$(date +%Y%m%d-%H%M%S).log || true
            git pull

            # 重新构建和启动服务
            docker-compose down
            docker builder prune -f
            docker-compose up -d --build

            # 等待服务启动并检查
            echo "Waiting for client service to start..."
            sleep 10
            
            if ! curl -s http://localhost:3000 > /dev/null; then
              echo "Client service is not responding!"
              docker-compose logs
              exit 1
            fi
            
            echo "Client deployment completed successfully!"
          ENDSSH 